CREATE DATABASE music;
use music;
CREATE TABLE Auteur(
    idAuteur INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom TEXT NOT NULL ,
    PRIMARY KEY (idAuteur)
);
CREATE TABLE Genre(
    idGenre INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nom VARCHAR(100) NOT NULL,
    PRIMARY KEY (idGenre)
    
);
CREATE TABLE Titre(
    idTitre INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    titre TEXT NOT NULL,
    PRIMARY KEY (idGenre)
    
);

CREATE TABLE AuTit(
    idTitre INT PRIMARY KEY NOT NULL,
    idGenre INT PRIMARY KEY NOT NULL,
    PRIMARY KEY (idGenre,idTitre)
    
);
